image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_STRATEGY: clone

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME='pwd'/.gradle

stages:
  - build
  - test
  - deployTest

build:
  stage: build
  only: 
    refs:
        - branches
  tags:
    - ugrad
  script: ./gradlew --build-cache assemble

test:
  stage: test
  only:
    refs:
      - branches
  except:
    - master
  tags:
    - ugrad
  script: ./gradlew check
  
deployStep:
  stage: deployTest
  tags:
    - ugrad
  artifacts:
    paths:
      - build/libs
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - echo ${CI_COMMIT_REF_NAME}
    - echo ${DEPLOY_SSH_KEY}
    - zip -r -y ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip build/libs
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip"  