image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_STRATEGY: clone

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME='pwd'/.gradle

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only: 
    refs:
        - branches
  tags:
    - ugrad
  artifacts:
    paths:
      - build/libs
  script: ./gradlew --build-cache assemble

test:
  stage: test
  only:
    refs:
      - branches
  except:
    - master
  tags:
    - ugrad
  script: ./gradlew check
  
deployStep:
  stage: deploy
  only:
    - develop
  tags:
    - ugrad
  artifacts:
    paths:
      - build/libs
  script:
    - chmod og-rwx ${TEST_DEPLOY_SSH_KEY}
    - zip -r ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip build/libs
    - scp -r -o StrictHostKeyChecking=no -i "${TEST_DEPLOY_SSH_KEY}" ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip "${TEST_DEPLOY_USER}@${TEST_DEPLOY_HOST}:${TEST_DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip"
